# -*- coding: utf-8 -*-
"""cryptobot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bl2uXisOIzDiCsNdPgheRJkC8gkBbfHM
"""

!pip install telebot

import telebot
import pandas_datareader.data as web
import yfinance as yf
import logging
import os
import time



brlusd = yf.Ticker("USDBRL=X")
brlhoje = brlusd.history(period='1d')
taxa_cambio = brlhoje['Close'][0]
print(taxa_cambio) ## Definir a taxa de câmbio Dolar/Real;

def preço_hoje(moeda):
    ticker = yf.Ticker(moeda)
    valorhoje = ticker.history(period='1d')
    return valorhoje['Close'][0] ## Retornar o valor da moeda que deseja pesquisar, de acordo com o Yahoo Finance;

brlusd = yf.Ticker("USDBRL-X")

btc = preço_hoje('BTC-USD')
btc_brl = btc*taxa_cambio
eth = preço_hoje('ETH-USD')
eth_brl = eth*taxa_cambio

api = '6428457244:AAEVv1BPcExbikW7cpjC86eUrZ9aKDzp1m0'

bot = telebot.TeleBot(api)

@bot.message_handler(commands=['ativarnot'])
def ativarnot(mensagem):
  bot.send_message(mensagem.chat.id, """Notificações ativadas!""")
  n = 0
  while n < 7:
        time.sleep(8400) ## Tempo de espera entre as mensagens.
        bot.send_message(mensagem.chat.id, f"""Valor do Bitcoin: {btc_brl.round()},
        Valor do Ethereum: {eth_brl.round()}
        """)
        n += 1 ## Função na qual o bot retornará o valor a cada X segundos.



@bot.message_handler(commands=['btc'])
def btc(mensagem):
  bot.send_message(mensagem.chat.id, f"O valor do Bitcoin agora é: {btc_brl.round()} Reais. ")



@bot.message_handler(commands=['eth'])
def eth(mensagem):
  bot.send_message(mensagem.chat.id, f"O valor do Ethereum agora é: {eth_brl.round()} Reais. ")

@bot.message_handler(commands=['cambiodolar'])
def taxacambio(mensagem):
  bot.send_message(mensagem.chat.id, f"A taxa de cambio atual é: {round(taxa_cambio, 2)} ")


def verificar(mensagem):
  return True

@bot.message_handler(func=verificar)
def prim_msg(mensagem):
  texto = """
  Olá, eu sou seu alerta de cripto diário! Escolha o que você quer fazer hoje.
  /ativarnot  Irá ativar as notificações diárias para o valor do BTC e do Ethereum durante 7 dias.
  /cambiodolar Informa a taxa de cambio do dólar hoje.
  /btc  Informa o valor do BTC no dia de hoje.
  /eth  Informa o valor do ETH no dia de hoje.

Não adianta responder qualquer outra coisa. Você só irá reiniciar o loop.
  """

  bot.reply_to(mensagem, texto)

bot.polling()

"""LINK DO BOT: https://web.telegram.org/k/#@CryyptoooBot
OBS.: Precisa de uma conta no Telegram pra funcionar
"""